services:
  Container01:
    image: autotrade_main_custom
    build:
      context: .
      dockerfile: "./Dockerfile.custom"
    environment:
      - ws_name=Container01
      - line_api_key=v6UMx7S3boe1ikRsn1GafAfgfx4kOacfPAul9Ppl0Yb
      - gemini_key=AIzaSyDpTC7cdIsf8uE6nQhhYVHwkd2I_Qqc03U
      - timeframe=2h #1m, 3m, 5m, 15m, 30m, 1h, 2h, 4h, 6h, 8h, 12h, 1d, 3d, 1w, 1M  
      - depth_limit_no=1000 # 5, 10, 20, 50, 100, 500, 1000
      - temperature=1.0 # 0.0 to 1.0
      - model=gemini-1.5-pro-latest # gemini-1.5-flash-latest or gemini-1.5-pro-latest
      - entry_time_minute=1
    container_name: Container01
    volumes:
      - .:/opt/app
  Container02:
    image: autotrade_main_custom
    build:
      context: .
      dockerfile: "./Dockerfile.custom"
    environment:
      - ws_name=Container02
      - line_api_key=d80pyNhSptaPHFIZG2GFYn37wUvYIxSp3bIRfLeW8o4
      - gemini_key=AIzaSyDn9uqxvJ8Tc3NC5H-KG2riJvEYSU0QmeU
      - timeframe=4h #1m, 3m, 5m, 15m, 30m, 1h, 2h, 4h, 6h, 8h, 12h, 1d, 3d, 1w, 1M
      - depth_limit_no=1000 # 5, 10, 20, 50, 100, 500, 1000
      - temperature=1.0 # 0.0 to 1.0
      - model=gemini-1.5-pro-latest # gemini-1.5-flash-latest or gemini-1.5-pro-latest
      - entry_time_minute=2
    container_name: Container02
    volumes:
      - .:/opt/app
  Container03:
    image: autotrade_main_custom
    build:
      context: .
      dockerfile: "./Dockerfile.custom"
    environment:
      - ws_name=Container03
      - line_api_key=Q3SX92u17IicdF5YQGQLX4SAq3eaudfRcRDfQuPC7iE
      - gemini_key=AIzaSyBmRvkhIPTzcY2gtKrQvkiBBDXipfrst58
      - timeframe=6h #1m, 3m, 5m, 15m, 30m, 1h, 2h, 4h, 6h, 8h, 12h, 1d, 3d, 1w, 1M
      - depth_limit_no=1000 # 5, 10, 20, 50, 100, 500, 1000
      - temperature=1.0 # 0.0 to 1.0
      - model=gemini-1.5-pro-latest # gemini-1.5-flash-latest or gemini-1.5-pro-latest
      - entry_time_minute=3
    container_name: Container03
    volumes:
      - .:/opt/app
  Container04:
    image: autotrade_main_custom
    build:
      context: .
      dockerfile: "./Dockerfile.custom"
    environment:
      - ws_name=Container04
      - line_api_key=S2USAACrgdOBBiDiaBZ6T5YHdWcj86dwkCwQ8754O1g
      - gemini_key=AIzaSyBxRlfNXCJXx4r3xZfGVnt-QWG97erqWiQ
      - timeframe=8h #1m, 3m, 5m, 15m, 30m, 1h, 2h, 4h, 6h, 8h, 12h, 1d, 3d, 1w, 1M
      - depth_limit_no=1000 # 5, 10, 20, 50, 100, 500, 1000
      - temperature=1.0 # 0.0 to 1.0
      - model=gemini-1.5-pro-latest # gemini-1.5-flash-latest or gemini-1.5-pro-latest
      - entry_time_minute=4
    container_name: Container04
    volumes:
      - .:/opt/app
  Container05:
    image: autotrade_main_custom
    build:
      context: .
      dockerfile: "./Dockerfile.custom"
    environment:
      - ws_name=Container05
      - line_api_key=Mr5PXsorSySN3PlJCTad2aRfS7dRswFpG7HWacW6J3X
      - gemini_key=AIzaSyAnjH33eZERDbzQWDQ_I_sQHF-S8Fnfnxc
      - timeframe=12h #1m, 3m, 5m, 15m, 30m, 1h, 2h, 4h, 6h, 8h, 12h, 1d, 3d, 1w, 1M
      - depth_limit_no=1000 # 5, 10, 20, 50, 100, 500, 1000
      - temperature=1.0 # 0.0 to 1.0
      - model=gemini-1.5-pro-latest # gemini-1.5-flash-latest or gemini-1.5-pro-latest
      - entry_time_minute=5
    container_name: Container05
    volumes:
      - .:/opt/app
  Container06:
    image: autotrade_main_custom
    build:
      context: .
      dockerfile: "./Dockerfile.custom"
    environment:
      - ws_name=Container06
      - line_api_key=HmxTAqP9ScNcYemx9e4M4s60s7JxjLykOD1vWblNojL
      - gemini_key=AIzaSyAEv69iG29oK4W3JZfI1QsvRp7qgyjif6k
      - timeframe=1d #1m, 3m, 5m, 15m, 30m, 1h, 2h, 4h, 6h, 8h, 12h, 1d, 3d, 1w, 1M
      - depth_limit_no=1000 # 5, 10, 20, 50, 100, 500, 1000
      - temperature=1.0 # 0.0 to 1.0
      - model=gemini-1.5-pro-latest # gemini-1.5-flash-latest or gemini-1.5-pro-latest
      - entry_time_minute=6
    container_name: Container06
    volumes:
      - .:/opt/app
  Container07:
    image: autotrade_main_custom
    build:
      context: .
      dockerfile: "./Dockerfile.custom"
    environment:
      - ws_name=Container07
      - line_api_key=BMQG1F3Ha1VS1KEynrbcnQf3j9hQ8vymEdqCzEZWyDM
      - gemini_key=AIzaSyCC8ZSfTOhTBJySY5MZlawgb-bHjYZn1NU
      - timeframe=3d #1m, 3m, 5m, 15m, 30m, 1h, 2h, 4h, 6h, 8h, 12h, 1d, 3d, 1w, 1M
      - depth_limit_no=1000 # 5, 10, 20, 50, 100, 500, 1000
      - temperature=1.0 # 0.0 to 1.0
      - model=gemini-1.5-pro-latest # gemini-1.5-flash-latest or gemini-1.5-pro-latest
      - entry_time_minute=7
    container_name: Container07
    volumes:
      - .:/opt/app
  Container08:
    image: autotrade_main_custom
    build:
      context: .
      dockerfile: "./Dockerfile.custom"
    environment:
      - ws_name=Container08
      - line_api_key=8j0FJjH5GqimPeMnsWFx8xgNeqYy6ECpViPaUml73bd
      - gemini_key=AIzaSyBHYfLHyvbG-iXfVlcLIAw_G0jRvcuINDE
      - timeframe=1w #1m, 3m, 5m, 15m, 30m, 1h, 2h, 4h, 6h, 8h, 12h, 1d, 3d, 1w, 1M
      - depth_limit_no=1000 # 5, 10, 20, 50, 100, 500, 1000
      - temperature=1.0 # 0.0 to 1.0
      - model=gemini-1.5-pro-latest # gemini-1.5-flash-latest or gemini-1.5-pro-latest
      - entry_time_minute=8
    container_name: Container08
    volumes:
      - .:/opt/app
  Container09:
    image: autotrade_main_custom
    build:
      context: .
      dockerfile: "./Dockerfile.custom"
    environment:
      - ws_name=Container09
      - line_api_key=qYmrfZbwuIRo3sbPLyuW0SNAbTYsltDTybqOaumfzuE
      - gemini_key=AIzaSyCWQxyXMkgMMaFtumXdCP09NbXWGYxrDYs
      - timeframe=4h #1m, 3m, 5m, 15m, 30m, 1h, 2h, 4h, 6h, 8h, 12h, 1d, 3d, 1w, 1M
      - depth_limit_no=100 # 5, 10, 20, 50, 100, 500, 1000
      - temperature=1.0 # 0.0 to 1.0
      - model=gemini-1.5-flash-latest # gemini-1.5-flash-latest or gemini-1.5-pro-latest
      - entry_time_minute=9
    container_name: Container09
    volumes:
      - .:/opt/app
  Container10:
    image: autotrade_main_custom
    build:
      context: .
      dockerfile: "./Dockerfile.custom"
    environment:
      - ws_name=Container10
      - line_api_key=xO1Ma0F4hPupAgZ3hef2O60Lh0XgxOazrltQ0qR9EWk
      - gemini_key=AIzaSyDQjOITlbsN3V3apRhYosBFimaZwcQryYk
      - timeframe=6h #1m, 3m, 5m, 15m, 30m, 1h, 2h, 4h, 6h, 8h, 12h, 1d, 3d, 1w, 1M
      - depth_limit_no=100 # 5, 10, 20, 50, 100, 500, 1000
      - temperature=1.0 # 0.0 to 1.0
      - model=gemini-1.5-flash-latest # gemini-1.5-flash-latest or gemini-1.5-pro-latest
      - entry_time_minute=10
    container_name: Container10
    volumes:
      - .:/opt/app
  Container11:
    image: autotrade_main_custom
    build:
      context: .
      dockerfile: "./Dockerfile.custom"
    environment:
      - ws_name=Container11
      - line_api_key=lfrAMTXAAOhXvnLhZ6cwIfkkhELmEgv9Thu6lSYPy8g
      - gemini_key=AIzaSyALWT-91aWLUQB8DRSP3OoA0RlS5rz4Ugk
      - timeframe=8h #1m, 3m, 5m, 15m, 30m, 1h, 2h, 4h, 6h, 8h, 12h, 1d, 3d, 1w, 1M
      - depth_limit_no=100 # 5, 10, 20, 50, 100, 500, 1000
      - temperature=1.0 # 0.0 to 1.0
      - model=gemini-1.5-flash-latest # gemini-1.5-flash-latest or gemini-1.5-pro-latest
      - entry_time_minute=11
    container_name: Container11
    volumes:
      - .:/opt/app
  Container12:
    image: autotrade_main_custom
    build:
      context: .
      dockerfile: "./Dockerfile.custom"
    environment:
      - ws_name=Container12
      - line_api_key=FslnTlFWBiFB6T20dv38olHdSER2Kfnk0YuSVjQjhOZ
      - gemini_key=AIzaSyBllqr6Bd1bDS8KCGtLHutUhRPz4c_mgVQ
      - timeframe=12h #1m, 3m, 5m, 15m, 30m, 1h, 2h, 4h, 6h, 8h, 12h, 1d, 3d, 1w, 1M
      - depth_limit_no=100 # 5, 10, 20, 50, 100, 500, 1000
      - temperature=1.0 # 0.0 to 1.0
      - model=gemini-1.5-flash-latest # gemini-1.5-flash-latest or gemini-1.5-pro-latest
      - entry_time_minute=12
    container_name: Container12
    volumes:
      - .:/opt/app
  Container13:
    image: autotrade_main_custom
    build:
      context: .
      dockerfile: "./Dockerfile.custom"
    environment:
      - ws_name=Container13
      - line_api_key=1I3JS94jK5r9SJM1a7zYqWAzubZ4AiBe2auf5avsJZv
      - gemini_key=AIzaSyBuUTskaNxQ3TCfcaGV_FaehhnyxBywlhU
      - timeframe=1d #1m, 3m, 5m, 15m, 30m, 1h, 2h, 4h, 6h, 8h, 12h, 1d, 3d, 1w, 1M
      - depth_limit_no=100 # 5, 10, 20, 50, 100, 500, 1000
      - temperature=1.0 # 0.0 to 1.0
      - model=gemini-1.5-flash-latest # gemini-1.5-flash-latest or gemini-1.5-pro-latest
      - entry_time_minute=13
    container_name: Container13
    volumes:
      - .:/opt/app
  Container14:
    image: autotrade_main_custom
    build:
      context: .
      dockerfile: "./Dockerfile.custom"
    environment:
      - ws_name=Container14
      - line_api_key=qfxIrX5VA8yH4uwDkVdffdgcI8yph3iXZxWhlhfzIcc
      - gemini_key=AIzaSyDZKy-_yHEtMqmVF-62t7Q7n5r_Ca0HRCU
      - timeframe=3d #1m, 3m, 5m, 15m, 30m, 1h, 2h, 4h, 6h, 8h, 12h, 1d, 3d, 1w, 1M
      - depth_limit_no=100 # 5, 10, 20, 50, 100, 500, 1000
      - temperature=1.0 # 0.0 to 1.0
      - model=gemini-1.5-flash-latest # gemini-1.5-flash-latest or gemini-1.5-pro-latest
      - entry_time_minute=14
    container_name: Container14
    volumes:
      - .:/opt/app
  Container15:
    image: autotrade_main_custom
    build:
      context: .
      dockerfile: "./Dockerfile.custom"
    environment:
      - ws_name=Container15
      - line_api_key=j4dam1oWU2EhslISH1HBig71OvYUIfDbG8U4ufMdvc5
      - gemini_key=AIzaSyBJBNOM9N8YwQNI9FsiSi8pDE1UGWmAtzs
      - timeframe=1w #1m, 3m, 5m, 15m, 30m, 1h, 2h, 4h, 6h, 8h, 12h, 1d, 3d, 1w, 1M
      - depth_limit_no=100 # 5, 10, 20, 50, 100, 500, 1000
      - temperature=1.0 # 0.0 to 1.0
      - model=gemini-1.5-flash-latest # gemini-1.5-flash-latest or gemini-1.5-pro-latest
      - entry_time_minute=15
    container_name: Container15
    volumes:
      - .:/opt/app
  # Container16:
  #   image: autotrade_main_custom
  #   build:
  #     context: .
  #     dockerfile: "./Dockerfile.custom"
  #   environment:
  #     - ws_name=Container16
  #     - line_api_key=gdCUGF5yi3hPY4riRqDPaCQdaR3LoHm2BwCIY5Bwx9O
  #     - gemini_key=AIzaSyDpTC7cdIsf8uE6nQhhYVHwkd2I_Qqc03U
  #     - timeframe=4h #1m, 3m, 5m, 15m, 30m, 1h, 2h, 4h, 6h, 8h, 12h, 1d, 3d, 1w, 1M
  #     - depth_limit_no=50 # 5, 10, 20, 50, 100, 500, 1000
  #     - temperature=1.0 # 0.0 to 1.0
  #     - model=gemini-1.5-pro-latest # gemini-1.5-pro-latest or gemini-1.5-pro-latest_vision\
  #     - entry_time_minute=1
  #   container_name: Container16
  #   volumes:
  #     - .:/opt/app
  # Container17:
  #   image: autotrade_main_custom
  #   build:
  #     context: .
  #     dockerfile: "./Dockerfile.custom"
  #   environment:
  #     - ws_name=Container17
  #     - line_api_key=iQd1bQIjfdlVD5uQDszRHNjku1dxtJPoBTfs5vYRCih
  #     - gemini_key=AIzaSyDn9uqxvJ8Tc3NC5H-KG2riJvEYSU0QmeU
  #     - timeframe=6h #1m, 3m, 5m, 15m, 30m, 1h, 2h, 4h, 6h, 8h, 12h, 1d, 3d, 1w, 1M
  #     - depth_limit_no=50 # 5, 10, 20, 50, 100, 500, 1000
  #     - temperature=1.0 # 0.0 to 1.0
  #     - model=gemini-1.5-pro-latest # gemini-1.5-pro-latest or gemini-1.5-pro-latest_vision
  #     - entry_time_minute=2
  #   container_name: Container17
  #   volumes:
  #     - .:/opt/app
  # Container18:
  #   image: autotrade_main_custom
  #   build:
  #     context: .
  #     dockerfile: "./Dockerfile.custom"
  #   environment:
  #     - ws_name=Container18
  #     - line_api_key=ucQoroZLGGaaIyECrFCwpqpPwk7TP1MG1H8QjCOrpIa
  #     - gemini_key=AIzaSyBmRvkhIPTzcY2gtKrQvkiBBDXipfrst58
  #     - timeframe=8h #1m, 3m, 5m, 15m, 30m, 1h, 2h, 4h, 6h, 8h, 12h, 1d, 3d, 1w, 1M
  #     - depth_limit_no=50 # 5, 10, 20, 50, 100, 500, 1000
  #     - temperature=1.0 # 0.0 to 1.0
  #     - model=gemini-1.5-pro-latest # gemini-1.5-pro-latest or gemini-1.5-pro-latest_vision
  #     - entry_time_minute=3
  #   container_name: Container18
  #   volumes:
  #     - .:/opt/app
  # Container19:
  #   image: autotrade_main_custom
  #   build:
  #     context: .
  #     dockerfile: "./Dockerfile.custom"
  #   environment:
  #     - ws_name=Container19
  #     - line_api_key=oQGI0hKmcOh4rk6VSSKKvaGTSMFm5RyCGuS2DxomaWy
  #     - gemini_key=AIzaSyBxRlfNXCJXx4r3xZfGVnt-QWG97erqWiQ
  #     - timeframe=12h #1m, 3m, 5m, 15m, 30m, 1h, 2h, 4h, 6h, 8h, 12h, 1d, 3d, 1w, 1M
  #     - depth_limit_no=50 # 5, 10, 20, 50, 100, 500, 1000
  #     - temperature=1.0 # 0.0 to 1.0
  #     - model=gemini-1.5-pro-latest # gemini-1.5-pro-latest or gemini-1.5-pro-latest_vision
  #     - entry_time_minute=4
  #   container_name: Container19
  #   volumes:
  #     - .:/opt/app
  # Container20:
  #   image: autotrade_main_custom
  #   build:
  #     context: .
  #     dockerfile: "./Dockerfile.custom"
  #   environment:
  #     - ws_name=Container20
  #     - line_api_key=QxGcd5CgSXVoZX7tl6bxyBst1pWdyrZdntMS8wUKqaS
  #     - gemini_key=AIzaSyAnjH33eZERDbzQWDQ_I_sQHF-S8Fnfnxc
  #     - timeframe=1d #1m, 3m, 5m, 15m, 30m, 1h, 2h, 4h, 6h, 8h, 12h, 1d, 3d, 1w, 1M
  #     - depth_limit_no=50 # 5, 10, 20, 50, 100, 500, 1000
  #     - temperature=1.0 # 0.0 to 1.0
  #     - model=gemini-1.5-pro-latest # gemini-1.5-pro-latest or gemini-1.5-pro-latest_vision
  #     - entry_time_minute=5
  #   container_name: Container20
  #   volumes:
  #     - .:/opt/app
  # Container21:
  #   image: autotrade_main_custom
  #   build:
  #     context: .
  #     dockerfile: "./Dockerfile.custom"
  #   environment:
  #     - ws_name=Container21
  #     - line_api_key=zgmQWabzTDv2dyuAck8CXDUbfcyOxu4Zx2BhS4kwRCG
  #     - gemini_key=AIzaSyAEv69iG29oK4W3JZfI1QsvRp7qgyjif6k
  #     - timeframe=4h #1m, 3m, 5m, 15m, 30m, 1h, 2h, 4h, 6h, 8h, 12h, 1d, 3d, 1w, 1M
  #     - depth_limit_no=100 # 5, 10, 20, 50, 100, 500, 1000
  #     - temperature=1.0 # 0.0 to 1.0
  #     - model=gemini-1.5-pro-latest # gemini-1.5-pro-latest or gemini-1.5-pro-latest_vision
  #     - entry_time_minute=6
  #   container_name: Container21
  #   volumes:
  #     - .:/opt/app
  # Container22:
  #   image: autotrade_main_custom
  #   build:
  #     context: .
  #     dockerfile: "./Dockerfile.custom"
  #   environment:
  #     - ws_name=Container22
  #     - line_api_key=wQiWi5Q8BRU0UgVjyy5ZEcjdJSlLCTRPt01v0xMYXir
  #     - gemini_key=AIzaSyCC8ZSfTOhTBJySY5MZlawgb-bHjYZn1NU
  #     - timeframe=6h #1m, 3m, 5m, 15m, 30m, 1h, 2h, 4h, 6h, 8h, 12h, 1d, 3d, 1w, 1M
  #     - depth_limit_no=100 # 5, 10, 20, 50, 100, 500, 1000
  #     - temperature=1.0 # 0.0 to 1.0
  #     - model=gemini-1.5-pro-latest # gemini-1.5-pro-latest or gemini-1.5-pro-latest_vision
  #     - entry_time_minute=7
  #   container_name: Container22
  #   volumes:
  #     - .:/opt/app
  # Container23:
  #   image: autotrade_main_custom
  #   build:
  #     context: .
  #     dockerfile: "./Dockerfile.custom"
  #   environment:
  #     - ws_name=Container23
  #     - line_api_key=UprirrsdhrKmBt9b3CVIUD2g3tE9x0gfQGB7paR3Jmz
  #     - gemini_key=AIzaSyBHYfLHyvbG-iXfVlcLIAw_G0jRvcuINDE
  #     - timeframe=8h  #1m, 3m, 5m, 15m, 30m, 1h, 2h, 4h, 6h, 8h, 12h, 1d, 3d, 1w, 1M
  #     - depth_limit_no=100 # 5, 10, 20, 50, 100, 500, 1000
  #     - temperature=1.0 # 0.0 to 1.0
  #     - model=gemini-1.5-pro-latest # gemini-1.5-pro-latest or gemini-1.5-pro-latest_vision
  #     - entry_time_minute=8
  #   container_name: Container23
  #   volumes:
  #     - .:/opt/app
  # Container24:
  #   image: autotrade_main_custom
  #   build:
  #     context: .
  #     dockerfile: "./Dockerfile.custom"
  #   environment:
  #     - ws_name=Container24
  #     - line_api_key=I6p5G5oa71ruflAMbcACh8uiVj53oaDXANuilVDnTvy
  #     - gemini_key=AIzaSyCWQxyXMkgMMaFtumXdCP09NbXWGYxrDYs
  #     - timeframe=12h #1m, 3m, 5m, 15m, 30m, 1h, 2h, 4h, 6h, 8h, 12h, 1d, 3d, 1w, 1M
  #     - depth_limit_no=100 # 5, 10, 20, 50, 100, 500, 1000
  #     - temperature=1.0 # 0.0 to 1.0
  #     - model=gemini-1.5-pro-latest # gemini-1.5-pro-latest or gemini-1.5-pro-latest_vision
  #     - entry_time_minute=9
  #   container_name: Container24
  #   volumes:
  #     - .:/opt/app
  # Container25:
  #   image: autotrade_main_custom
  #   build:
  #     context: .
  #     dockerfile: "./Dockerfile.custom"
  #   environment:
  #     - ws_name=Container25
  #     - line_api_key=YEYWwR91ecRFBlvAO5PqJe5zhsd8AhyarkhqdlbAqjp
  #     - gemini_key=AIzaSyDQjOITlbsN3V3apRhYosBFimaZwcQryYk
  #     - timeframe=1d #1m, 3m, 5m, 15m, 30m, 1h, 2h, 4h, 6h, 8h, 12h, 1d, 3d, 1w, 1M
  #     - depth_limit_no=100 # 5, 10, 20, 50, 100, 500, 1000
  #     - temperature=1.0 # 0.0 to 1.0
  #     - model=gemini-1.5-pro-latest # gemini-1.5-pro-latest or gemini-1.5-pro-latest_vision
  #     - entry_time_minute=10
  #   container_name: Container25
  #   volumes:
  #     - .:/opt/app
  # Container26:
  #   image: autotrade_main_custom
  #   build:
  #     context: .
  #     dockerfile: "./Dockerfile.custom"
  #   environment:
  #     - ws_name=Container26
  #     - line_api_key=eKOWhwHHuSIv8Ru8r62YeavFWa4tgdJa0hQoM8f13T6
  #     - gemini_key=AIzaSyALWT-91aWLUQB8DRSP3OoA0RlS5rz4Ugk
  #     - timeframe=4h #1m, 3m, 5m, 15m, 30m, 1h, 2h, 4h, 6h, 8h, 12h, 1d, 3d, 1w, 1M
  #     - depth_limit_no=500 # 5, 10, 20, 50, 100, 500, 1000
  #     - temperature=1.0 # 0.0 to 1.0
  #     - model=gemini-1.5-pro-latest # gemini-1.5-pro-latest or gemini-1.5-pro-latest_vision
  #     - entry_time_minute=11
  #   container_name: Container26
  #   volumes:
  #     - .:/opt/app
  # Container27:
  #   image: autotrade_main_custom
  #   build:
  #     context: .
  #     dockerfile: "./Dockerfile.custom"
  #   environment:
  #     - ws_name=Container27
  #     - line_api_key=tfZeqQHO6fYA4XkDwGE1etrbSp9QJm5NrV08TpOrCGm
  #     - gemini_key=AIzaSyBllqr6Bd1bDS8KCGtLHutUhRPz4c_mgVQ
  #     - timeframe=6h #1m, 3m, 5m, 15m, 30m, 1h, 2h, 4h, 6h, 8h, 12h, 1d, 3d, 1w, 1M
  #     - depth_limit_no=500 # 5, 10, 20, 50, 100, 500, 1000
  #     - temperature=1.0 # 0.0 to 1.0
  #     - model=gemini-1.5-pro-latest # gemini-1.5-pro-latest or gemini-1.5-pro-latest_vision
  #     - entry_time_minute=12
  #   container_name: Container27
  #   volumes:
  #     - .:/opt/app
  # Container28:
  #   image: autotrade_main_custom
  #   build:
  #     context: .
  #     dockerfile: "./Dockerfile.custom"
  #   environment:
  #     - ws_name=Container28
  #     - line_api_key=e02RuguqJ2HAHwiAzi7HEg7DPN56R3br7s2IGBlQulF
  #     - gemini_key=AIzaSyBuUTskaNxQ3TCfcaGV_FaehhnyxBywlhU
  #     - timeframe=8h  #1m, 3m, 5m, 15m, 30m, 1h, 2h, 4h, 6h, 8h, 12h, 1d, 3d, 1w, 1M
  #     - depth_limit_no=500 # 5, 10, 20, 50, 100, 500, 1000
  #     - temperature=1.0 # 0.0 to 1.0
  #     - model=gemini-1.5-pro-latest # gemini-1.5-pro-latest or gemini-1.5-pro-latest_vision
  #     - entry_time_minute=13
  #   container_name: Container28
  #   volumes:
  #     - .:/opt/app
  # Container29:
  #   image: autotrade_main_custom
  #   build:
  #     context: .
  #     dockerfile: "./Dockerfile.custom"
  #   environment:
  #     - ws_name=Container29
  #     - line_api_key=A4za9hEJIgFLgxhWmSGA4E8SHIhBY0AfYEBEm9ZTDbj
  #     - gemini_key=AIzaSyDZKy-_yHEtMqmVF-62t7Q7n5r_Ca0HRCU
  #     - timeframe=12h #1m, 3m, 5m, 15m, 30m, 1h, 2h, 4h, 6h, 8h, 12h, 1d, 3d, 1w, 1M
  #     - depth_limit_no=500 # 5, 10, 20, 50, 100, 500, 1000
  #     - temperature=1.0 # 0.0 to 1.0
  #     - model=gemini-1.5-pro-latest # gemini-1.5-pro-latest or gemini-1.5-pro-latest_vision
  #     - entry_time_minute=14
  #   container_name: Container29
  #   volumes:
  #     - .:/opt/app
  # Container30:
  #   image: autotrade_main_custom
  #   build:
  #     context: .
  #     dockerfile: "./Dockerfile.custom"
  #   environment:
  #     - ws_name=Container30
  #     - line_api_key=Ld0b7uz25QbQlofmEE7xhVMTR1tJPMioOB6m3UslhCk
  #     - gemini_key=AIzaSyBJBNOM9N8YwQNI9FsiSi8pDE1UGWmAtzs
  #     - timeframe=1d #1m, 3m, 5m, 15m, 30m, 1h, 2h, 4h, 6h, 8h, 12h, 1d, 3d, 1w, 1M
  #     - depth_limit_no=500 # 5, 10, 20, 50, 100, 500, 1000
  #     - temperature=1.0 # 0.0 to 1.0
  #     - model=gemini-1.5-pro-latest # gemini-1.5-pro-latest or gemini-1.5-pro-latest_vision
  #     - entry_time_minute=15
  #   container_name: Container30
  #   volumes:
  #     - .:/opt/app