# Use the official Python 3.12 image as the base image
FROM python:3.12

# Update the package list and install necessary system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    libssl-dev \
    zlib1g-dev \
    libbz2-dev \
    libreadline-dev \
    libsqlite3-dev \
    wget \
    curl \
    llvm \
    libc6-dev \
    libedit-dev \
    libncursesw5-dev \
    xz-utils \
    tk-dev \
    libxml2-dev \
    libxmlsec1-dev \
    libffi-dev \
    liblzma-dev

# Download and install TA-Lib
RUN wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz && \
    tar -xzf ta-lib-0.4.0-src.tar.gz && \
    cd ta-lib && \
    ./configure --prefix=/usr/local && \
    make && \
    make install && \
    cd .. && \
    rm -rf ta-lib*

# Upgrade pip, setuptools, and wheel
RUN python3 -m pip install --no-cache-dir -U pip setuptools wheel

# Install Python libraries
RUN python3 -m pip install --no-cache-dir TA-Lib             # Technical Analysis Library
RUN python3 -m pip install --no-cache-dir grpcio             # gRPC for remote procedure calls
RUN python3 -m pip install --no-cache-dir pandas             # Data analysis and manipulation
RUN python3 -m pip install --no-cache-dir google-generativeai # Google Generative AI
RUN python3 -m pip install --no-cache-dir plotly             # Interactive plotting library
RUN python3 -m pip install --no-cache-dir matplotlib         # Plotting library
RUN python3 -m pip install --no-cache-dir mplfinance         # Matplotlib Finance for candlestick charts
RUN python3 -m pip install --no-cache-dir pillow             # Image processing library
RUN python3 -m pip install --no-cache-dir yfinance            # Yahoo Finance API
RUN python3 -m pip install --no-cache-dir pytickersymbols    # Ticker symbols for various exchanges
RUN python3 -m pip install --no-cache-dir pdfkit             # PDF generation library
RUN python3 -m pip install --no-cache-dir pdf2image         # Convert PDF to images
RUN python3 -m pip install --no-cache-dir img2pdf         # Convert images to PDF
RUN python3 -m pip install --no-cache-dir PyPDF2             # PDF manipulation library
RUN python3 -m pip install --no-cache-dir pyyaml             # YAML parsing and emitting library

# Set the default command to run when the container starts
CMD ["python", "/opt/app/main.py"]